version: "3.3"
services:

    webserver:
      image: nginx:latest
      container_name: jtl-webserver
      working_dir: /application
      volumes:
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8011:80"

    php-fpm:
      build: docker/php-fpm
      container_name: jtl-php-fpm
      working_dir: /application
      volumes:
        - .:/application/source

#    You need a Database? Here we go!
#    develdb:
#      image: mariadb:latest
#      container_name: jtl-mariadb
#      environment:
#        MYSQL_ROOT_PASSWORD: 'root'
#        MYSQL_DATABASE: 'skeleton'
#        MYSQL_USER: 'skeleton'
#        MYSQL_PASSWORD: 'pass'
#      volumes:
#        - ./var/dbvolume:/var/lib/mysql
#        - ./docker/initdb:/docker-entrypoint-initdb.d
#      ports:
#        - "3306:3306"
#      working_dir: /application